In [ ]:
#O algoritmo irá classificar os vinhos entre branco e tinto
#Os dados serão divididos para treino e para teste

In [2]:
#Importar bibliotecas
import pandas as pd

In [6]:
#Importar dados
wineDs = pd.read_csv('C:/Users/Laisla Francisco/Documents/Python/wine_dataset.csv')

In [7]:
#Visualizar 5 primeiras linhas do arquivo
wineDs.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [9]:
#Transformar coluna de branco/tinto em valor numérico
#tinto = 0 e branco = 1
wineDs['style'] = wineDs['style'].replace('red', 0)
wineDs['style'] = wineDs['style'].replace('white', 1)
wineDs.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0

In [10]:
#Separar variáveis entre preditoras e variável alvo ( style = branco/tinto)
#y armazena a coluna style
y = wineDs['style']
#x armazena todas colunas exceto a style
x = wineDs.drop('style', axis = 1)

In [18]:
#Separar dados para treino e para teste
from sklearn.model_selection import train_test_split

#Irá utilizar 30% dos dados para teste e os 70% restantes de treino
#4 saídas nas variáveis de treino e teste
x_treino, x_teste, y_treino, y_teste = train_test_split(x,y, test_size = 0.3)

#Visualizar qtd de dados de treino e teste
print(x_treino.shape)
print(x_teste.shape)

(4547, 12)
(1950, 12)

In [19]:
#Importar algoritmo de arvore de decisão
#Roda em cima dos dados de treino
from sklearn.ensemble import ExtraTreesClassifier

#A variável modelo recebe o algoritmo
modelo = ExtraTreesClassifier()
#O algoritmo é aplicado aos dados de treino
modelo.fit(x_treino, y_treino)

#Resultados
#Os dados foram relacionados no treino
#A função score compara os dados reais de teste, passa pro algoritmo
#Ele tenta prever a classe de cada amostra
#Exibe o quanto o algoritmo acertou dos dados inseridos
resultado = modelo.score(x_teste, y_teste)
print('Acurácia: ', resultado)

Acurácia:  0.9984615384615385

In [23]:
#Filtrar três amostras aleatórias
y_teste[400:403]

3240    1
3915    1
3770    1
Name: style, dtype: int64

In [24]:
x_teste[400:403]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
3240,6.4,0.22,0.49,7.5,0.054,42.0,151.0,0.9948,3.27,0.52,10.1,6
3915,7.4,0.20,0.31,1.6,0.038,34.0,116.0,0.9912,3.25,0.39,12.0,7
3770,7.4,0.19,0.30,12.8,0.053,48.5,229.0,0.9986,3.14,0.49,9.1,7

In [27]:
#Verificar se o modelo consegue prever as variáveis
previsoes = modelo.predict(x_teste[400:403])
previsoes

array([1, 1, 1], dtype=int64)

In [ ]:
#O algoritmo treinado com o modelo realizou a previsão dos
#itens aleatórios 400:403 onde foi previsto que os três vinhos eram brancos
#e na lista teste y comprovamos o resultado